export const jobs = [
  { id: 1, title: 'Software Engineer', company: 'TechNova Ltd.', initials: 'TN', location: 'Dhaka', salary: '৳50,000–70,000', type: 'Full Time', mode: 'Hybrid', experience: '2+ years', match: 94, verified: true, posted: '2 hours ago', industry: 'Technology', skills: ['Python', 'SQL', 'REST APIs', 'Git'], description: 'Build dependable products used by growing businesses across Bangladesh. You will work with a collaborative product team to design, ship, and improve customer-facing software.', responsibilities: ['Build and maintain scalable backend services', 'Collaborate with product and design teams', 'Review code and improve engineering practices'], qualifications: ["Bachelor’s degree in CSE or equivalent experience", '2+ years of software development', 'Strong Python and SQL skills'], benefits: ['Flexible hybrid work', 'Learning budget', 'Health coverage', 'Two festival bonuses'], deadline: 'October 20, 2026' },
  { id: 2, title: 'Data Analyst', company: 'DataPulse', initials: 'DP', location: 'Dhaka', salary: '৳45,000–60,000', type: 'Full Time', mode: 'Remote', experience: '1–3 years', match: 89, verified: true, posted: '1 day ago', industry: 'Analytics', skills: ['SQL', 'Python', 'Power BI', 'Excel'], description: 'Turn complex datasets into clear insights that help teams make confident decisions.', responsibilities: ['Create dashboards and recurring reports', 'Analyze business trends', 'Partner with operations teams'], qualifications: ['Strong SQL and spreadsheet skills', 'Clear written communication', 'Experience with a BI tool'], benefits: ['Remote first', 'Internet allowance', 'Annual retreat'], deadline: 'October 24, 2026' },
  { id: 3, title: 'Junior ML Engineer', company: 'Orbit AI', initials: 'OA', location: 'Chattogram', salary: '৳55,000–80,000', type: 'Full Time', mode: 'On-site', experience: '1+ year', match: 86, verified: true, posted: '2 days ago', industry: 'Artificial Intelligence', skills: ['Python', 'Machine Learning', 'Pandas', 'Git'], description: 'Help deliver practical machine learning features from prototype to production.', responsibilities: ['Train and evaluate models', 'Prepare datasets', 'Document experiments'], qualifications: ['Python proficiency', 'ML fundamentals', 'Curiosity and ownership'], benefits: ['Mentorship', 'Research days', 'Lunch allowance'], deadline: 'November 2, 2026' },
  { id: 4, title: 'Frontend Developer', company: 'PixelCraft', initials: 'PC', location: 'Sylhet', salary: '৳40,000–58,000', type: 'Contract', mode: 'Remote', experience: '2+ years', match: 81, verified: false, posted: '3 days ago', industry: 'Design & Software', skills: ['React', 'JavaScript', 'CSS', 'Figma'], description: 'Create polished, accessible interfaces for international product teams.', responsibilities: ['Build responsive interfaces', 'Maintain component systems', 'Improve web performance'], qualifications: ['Strong React skills', 'Attention to visual detail', 'Accessible HTML knowledge'], benefits: ['Flexible hours', 'Remote work', 'Project bonus'], deadline: 'October 29, 2026' },
  { id: 5, title: 'Product Designer', company: 'Mango Labs', initials: 'ML', location: 'Dhaka', salary: '৳60,000–85,000', type: 'Full Time', mode: 'Hybrid', experience: '3+ years', match: 72, verified: true, posted: '4 days ago', industry: 'Technology', skills: ['Figma', 'UX Research', 'Prototyping'], description: 'Shape simple, useful experiences for a fast-growing consumer platform.', responsibilities: ['Own end-to-end product design', 'Run lightweight research', 'Evolve the design system'], qualifications: ['Strong portfolio', '3+ years product design', 'Systems thinking'], benefits: ['Design conference budget', 'Hybrid work', 'Health coverage'], deadline: 'November 6, 2026' },
  { id: 6, title: 'QA Automation Engineer', company: 'CloudCore', initials: 'CC', location: 'Dhaka', salary: '৳48,000–65,000', type: 'Full Time', mode: 'Hybrid', experience: '2+ years', match: 78, verified: true, posted: '5 days ago', industry: 'Cloud Services', skills: ['JavaScript', 'Playwright', 'API Testing', 'Git'], description: 'Build automation that keeps cloud products stable and delightful.', responsibilities: ['Create end-to-end tests', 'Investigate regressions', 'Improve release confidence'], qualifications: ['Automation experience', 'API testing knowledge', 'Clear debugging skills'], benefits: ['Flexible hours', 'Certification support', 'Provident fund'], deadline: 'November 10, 2026' },
];

export const applicationsSeed = [
  { id: 1, jobId: 2, title: 'Data Analyst', company: 'DataPulse', status: 'Under Review', date: 'Sep 22, 2026' },
  { id: 2, jobId: 3, title: 'Junior ML Engineer', company: 'Orbit AI', status: 'Interview', date: 'Sep 18, 2026', interview: 'Sep 29 · 11:00 AM' },
  { id: 3, jobId: 6, title: 'QA Automation Engineer', company: 'CloudCore', status: 'Applied', date: 'Sep 15, 2026' },
];

export const applicants = [
  { id: 1, name: 'Nadia Rahman', role: 'Software Engineer', match: 94, experience: '2.5 years', education: 'BSc CSE', skills: ['Python', 'SQL', 'Git'], stage: 'New' },
  { id: 2, name: 'Farhan Ahmed', role: 'Software Engineer', match: 88, experience: '3 years', education: 'BSc SWE', skills: ['Python', 'Django', 'AWS'], stage: 'Shortlisted' },
  { id: 3, name: 'Tasnim Chowdhury', role: 'Software Engineer', match: 76, experience: '2 years', education: 'BSc CSE', skills: ['Java', 'SQL', 'Docker'], stage: 'Review' },
  { id: 4, name: 'Sakib Hasan', role: 'Software Engineer', match: 71, experience: '1.5 years', education: 'BSc IT', skills: ['Node.js', 'MongoDB'], stage: 'New' },
];
